FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore src/JeeSiteNET.Web.Api/JeeSiteNET.Web.Api.csproj
RUN dotnet publish src/JeeSiteNET.Web.Api/JeeSiteNET.Web.Api.csproj -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
COPY --from=build /app .
ENTRYPOINT ["dotnet", "JeeSiteNET.Web.Api.dll"]
